#Nume: Usurelu
#Prenume: Catalin-Constantin
#Grupa: 333CA

CXX = mpic++

MAIN = main
MAIN_SRC = main.cpp

.PHONY : build, clean

build:
	$(CXX) -o $(MAIN) $(MAIN_SRC)

clean :
	rm -f $(MAIN)
	rm -f *.o
